name: deploy to aws

on:
  push:
    branches:
    - main

jobs:
  deploy_to_aws_lambda_function:
    name: deploy_to_aws_lambda_function
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - 
      name: command1
      run: ls -la
    - 
      name: creating a zip package
      run: zip python.zip lambda_function.py
    - 
      name: checking the list files
      run: ls -la
    - 
      name: publish to lambda
      run: aws lambda update-function-code --function-name WorkFlowFunction --zip-file fileb://python.zip
